2024-01-11 18:50:20.542 | WARNING  | aria2p.downloads:following:722 - Can't find download with GID a89a9c5ac990e6ef, try to update download 0a6635c602761000 (140148908930208
2024-01-11 18:50:20.542 | TRACE    | aria2p.downloads:following:725 - GID a89a9c5ac990e6ef is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1640, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f76fdb4a750>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1142, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f76fd7fd620>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f76fd81b380>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f76fd819670>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 343, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f76fdbc5ac0>
    │    └ <function WorkerPool._perform_spawn at 0x7f76fd7fd800>
    └ <execnet.gateway_base.WorkerPool object at 0x7f76fd81b380>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f76fd7fd4e0>
    └ <execnet.gateway_base.Reply object at 0x7f76fdbc5ac0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f76fd819670>>
    └ <execnet.gateway_base.Reply object at 0x7f76fdbc5ac0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1157, in executetask
    exec(co, loc)
         │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
         └ <code object <module> at 0x55ee9f75ea80, file "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 1>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 355, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f76fd99caa0>
    │      │    └ <HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f76fc468b90>
    └ <_pytest.config.Config object at 0x7f76fd99caa0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'config': <_pytest.config.Config object at 0x7f76fd99caa0>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f76fd99caa0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f76fdbad760>
           └ <_pytest.config.PytestPluginManager object at 0x7f76fdbf3140>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f76fd99caa0>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f76fc4d5620>
           │            └ <_pytest.config.Config object at 0x7f76fd99caa0>
           └ <function wrap_session at 0x7f76fc4d5580>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │       │            │    └ <_pytest.config.Config object at 0x7f76fd99caa0>
    │       │            └ <function _main at 0x7f76fc4d5620>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f76fc468b90>
    └ <_pytest.config.Config object at 0x7f76fd99caa0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f76fdbad760>
           └ <_pytest.config.PytestPluginManager object at 0x7f76fdbf3140>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='140149036001200', plugin=<__channelexec__.WorkerInteractor object at 0x7f76fd81a7b0>>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 157, in pytest_runtestloop
    self.run_one_test()
    │    └ <function WorkerInteractor.run_one_test at 0x7f76fc26c040>
    └ <__channelexec__.WorkerInteractor object at 0x7f76fd81a7b0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 174, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_followed_by>
    │    │      │    │                            └ <Function test_following>
    │    │      │    └ <HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f76fc468b90>
    │    └ <_pytest.config.Config object at 0x7f76fd99caa0>
    └ <__channelexec__.WorkerInteractor object at 0x7f76fd81a7b0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'item': <Function test_following>, 'nextitem': <Function test_followed_by>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_following>, 'nextitem': <Function test_followed_by>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f76fdbad760>
           └ <_pytest.config.PytestPluginManager object at 0x7f76fdbf3140>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_following>, <Function test_followed_by>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.12...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pytest_rerunfailures.py", line 541, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_followed_by>
              │               └ <Function test_following>
              └ <function runtestprotocol at 0x7f76fc4d47c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_following>
    │       │      └ <function call_and_report at 0x7f76fc4d4b80>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_downloads.py::TestDownloadClass::test_following' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_following>
           └ <function call_runtest_hook at 0x7f76fc4d4d60>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f76fc4d4fe0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f76f6f8f7e0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_following>
            └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ False
           │    │         │    │     │    │           └ {'item': <Function test_following>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_following>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f76fdbad760>
           └ <_pytest.config.PytestPluginManager object at 0x7f76fdbf3140>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_following>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f76fc51f880>
    └ <Function test_following>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_following>
    │    └ <property object at 0x7f76fc636430>
    └ <Function test_following>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'pyfuncitem': <Function test_following>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_following>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f76fdbad760>
           └ <_pytest.config.PytestPluginManager object at 0x7f76fdbf3140>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_following>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'server': <tests.conftest.Aria2Server object at 0x7f76f5eeb2c0>}
             └ <bound method TestDownloadClass.test_following of <tests.test_downloads.TestDownloadClass object at 0x7f76f6f17d70>>

  File "/media/data/dev/aria2p/tests/test_downloads.py", line 184, in test_following
    assert self.download.following is None
           │    │        └ <property object at 0x7f76f745c720>
           │    └ <aria2p.downloads.Download object at 0x7f76f5eeb4a0>
           └ <tests.test_downloads.TestDownloadClass object at 0x7f76f6f17d70>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 720, in following
    self._following = self.api.get_download(following_id)
    │    │            │    │   │            └ 'a89a9c5ac990e6ef'
    │    │            │    │   └ <function API.get_download at 0x7f76f74c8a40>
    │    │            │    └ API(Client(host='http://localhost', port=15639, secret='********'))
    │    │            └ <aria2p.downloads.Download object at 0x7f76f5eeb4a0>
    │    └ None
    └ <aria2p.downloads.Download object at 0x7f76f5eeb4a0>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 264, in get_download
    return Download(self, self.client.tell_status(gid))
           │        │     │    │      │           └ 'a89a9c5ac990e6ef'
           │        │     │    │      └ <function Client.tell_status at 0x7f76f743b600>
           │        │     │    └ Client(host='http://localhost', port=15639, secret='********')
           │        │     └ API(Client(host='http://localhost', port=15639, secret='********'))
           │        └ API(Client(host='http://localhost', port=15639, secret='********'))
           └ <class 'aria2p.downloads.Download'>

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 854, in tell_status
    return self.call(self.TELL_STATUS, [gid, keys])  # type: ignore
           │    │    │    │             │    └ None
           │    │    │    │             └ 'a89a9c5ac990e6ef'
           │    │    │    └ 'aria2.tellStatus'
           │    │    └ Client(host='http://localhost', port=15639, secret='********')
           │    └ <function Client.call at 0x7f76f743aa20>
           └ Client(host='http://localhost', port=15639, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 258, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.tellStatus", "id": -1, "params": ["a89a9c5ac990e6ef"]}'
           │    │            │    └ <function Client.post at 0x7f76f743ac00>
           │    │            └ Client(host='http://localhost', port=15639, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f76f743ad40>)>
           └ Client(host='http://localhost', port=15639, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 380, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID a89a9c5ac990e6ef is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f76f743aca0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID a89a9c5ac990e6ef is not found
