2024-01-10 11:23:39,109 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-10 11:23:39,110 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-10 11:23:39,110 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-10 11:23:39,110 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['pyqtchat8741/server/server.py']
2024-01-10 11:23:39,110 DEBUG server.py Аргументы успешно загружены.
2024-01-10 11:23:39,113 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-10 11:24:55,154 INFO core.py Установлено соедение с ПК ('127.0.0.1', 60826)
2024-01-10 11:24:55,657 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>,) , {}. Вызов из модуля core.utils
2024-01-10 11:24:55,658 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704875095.159307, 'user': {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-10 11:24:55,658 DEBUG core.py Start auth process for {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-10 11:24:55,665 DEBUG core.py Correct username, starting passwd check.
2024-01-10 11:24:55,665 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>, {'response': 511, 'bin': 'b7d0a8145e3b8db005f33665b700f4365ef0dc339cece116368136d230c9779d5edb298b98af5f6697b8c57f0dea8862efa39b2cbfd16347f866dcc2aa1cfdcf'}) , {}. Вызов из модуля core.utils
2024-01-10 11:24:55,665 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>,) , {}. Вызов из модуля core.utils
2024-01-10 11:24:55,668 DEBUG core.py Auth message = {'response': 511, 'bin': 'b7d0a8145e3b8db005f33665b700f4365ef0dc339cece116368136d230c9779d5edb298b98af5f6697b8c57f0dea8862efa39b2cbfd16347f866dcc2aa1cfdcf'}
2024-01-10 11:24:55,668 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-10 11:24:56,192 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>,) , {}. Вызов из модуля core.utils
2024-01-10 11:24:56,193 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704875095.66898, 'account_name': 'one'}
2024-01-10 11:24:56,197 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>, {'response': 202, 'data_list': ['one']}) , {}. Вызов из модуля core.utils
2024-01-10 11:24:56,698 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>,) , {}. Вызов из модуля core.utils
2024-01-10 11:24:56,699 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704875096.203447, 'user': 'one'}
2024-01-10 11:24:56,707 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-10 11:25:06,230 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60826)>,) , {}. Вызов из модуля core.utils
2024-01-10 11:25:06,230 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1704875105.891412, 'account_name': 'one'}
2024-01-10 11:25:06,230 INFO core.py Клиент ('127.0.0.1', 60826) отключился от сервера.
